In [23]:
import pandas as pd

In [24]:
dfTurmas = pd.read_csv("../CSVs/Finais/turmas_geral.csv", sep=";")
dfAvaliacoesDocentes = pd.read_csv("../CSVs/Finais/docentes_e_avaliação_criptografado.csv", sep=";")

In [25]:
dfTurmas = dfTurmas.drop(labels="ano", axis=1)
dfTurmas = dfTurmas.drop(labels="periodo", axis=1)
dfTurmas = dfTurmas.drop(labels="total_alunos", axis=1)

dfTurmas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170940 entries, 0 to 170939
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   id_turma                              170940 non-null  int64
 1   media_final_geral                     170940 non-null  float64
 2   qtd_aprovado                          170940 non-null  int64
 3   qtd_desistencia                       170940 non-null  int64
 4   qtd_reprovado_por_média_e_por_faltas  170940 non-null  int64
 5   qtd_trancado                          170940 non-null  int64
 6   qtd_aprovado_por_nota                 170940 non-null  int64
 7   qtd_reprovado                         170940 non-null  int64
 8   qtd_reprovado_por_faltas              170940 non-null  int64
 9   qtd_reprovado_por_nota_e_falta        170940 non-null  int64
 10  qtd_reprovado_por_nota                170940 non-null  int64
dtypes: float64(1), int64(10)
memory usage: 14.3 MB

In [26]:
df_merged = pd.merge(
    left=dfAvaliacoesDocentes,          # DataFrame da esquerda (base)
    right=dfTurmas,       # DataFrame da direita (a ser unido)
    on='id_turma',          # Coluna de junção
    how='left'              # Tipo de JOIN (LEFT, RIGHT, INNER, OUTER)
)

In [27]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126294 entries, 0 to 126293
Data columns (total 28 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   nome                                  126294 non-null  object
 1   sexo                                  126294 non-null  object
 2   formacao                              126294 non-null  object
 3   vinculo                               126294 non-null  object
 4   categoria                             126294 non-null  object
 5   classe_funcional                      126294 non-null  object
 6   lotacao                               126294 non-null  object
 7   id_turma                              126294 non-null  int64
 8   ano                                   126294 non-null  int64
 9   periodo                               126294 non-null  int64
 10  qtd_discentes                         126294 non-null  int64
 11  postura_profissional_media            126294 non-null  float64
 12  postura_profissional_DP               126294 non-null  float64
 13  atuacao_profissional_media            126294 non-null  float64
 14  atuacao_profissional_DP               126294 non-null  float64
 15  autoavaliacao_aluno_media             69850 non-null   float64
 16  autoavaliacao_aluno_DP                69850 non-null   float64
 17  ano_admissao                          126294 non-null  int64
 18  media_final_geral                     125801 non-null  float64
 19  qtd_aprovado                          125801 non-null  float64
 20  qtd_desistencia                       125801 non-null  float64
 21  qtd_reprovado_por_média_e_por_faltas  125801 non-null  float64
 22  qtd_trancado                          125801 non-null  float64
 23  qtd_aprovado_por_nota                 125801 non-null  float64
 24  qtd_reprovado                         125801 non-null  float64
 25  qtd_reprovado_por_faltas              125801 non-null  float64
 26  qtd_reprovado_por_nota_e_falta        125801 non-null  float64
 27  qtd_reprovado_por_nota                125801 non-null  float64
dtypes: float64(16), int64(5), object(7)
memory usage: 27.0+ MB

In [28]:
df_nulos = df_merged[df_merged['media_final_geral'].isna()]

In [29]:
df_nulos['lotacao'].unique()

array(['DEPARTAMENTO DE PEDIATRIA', 'DEPARTAMENTO DE FISIOTERAPIA',
       'DEPARTAMENTO DE CIÊNCIAS ADMINISTRATIVAS - DEPAD',
       'DEPARTAMENTO DE TOCO-GINECOLOGIA', 'DEPARTAMENTO DE CIRURGIA',
       'DEPARTAMENTO DE ADMINISTRAÇÃO PUBLICA E GESTÃO SOCIAL',
       'INSTITUTO DE QUÍMICA',
       'ESCOLA MULTICAMPI DE CIÊNCIAS MÉDICAS DO RIO GRANDE DO NORTE',
       'DEPARTAMENTO DE MEDICINA CLÍNICA', 'DEPARTAMENTO DE INFECTOLOGIA',
       'DEPARTAMENTO DE MEDICINA INTEGRADA', 'DEPARTAMENTO DE NUTRIÇÃO',
       'EBSERH - GERÊNCIA DE ENSINO E PESQUISA',
       'DEPARTAMENTO DE MATEMÁTICA',
       'DEPARTAMENTO DE PRÁTICAS EDUCACIONAIS E CURRÍCULO',
       'DEPARTAMENTO DE SAÚDE COLETIVA', 'DEPARTAMENTO DE ODONTOLOGIA',
       'DEPARTAMENTO DE PATOLOGIA',
       'FACULDADE DE CIÊNCIAS DA SAÚDE DO TRAIRI - FACISA',
       'DEPARTAMENTO DE LINGUAS E LITERATURAS ESTRANGEIRAS MODERNAS',
       'DEPARTAMENTO DE CIÊNCIAS SOCIAIS',
       'FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOCIAIS DO SERIDÓ - FELCS',
       'INSTITUTO DO CÉREBRO', 'CENTRO DE CIÊNCIAS SOCIAIS APLICADAS',
       'SUPERINTENDÊNCIA DO HUOL - EBSERH'], dtype=object)

In [30]:
df_nulos[df_nulos['lotacao'] == "DEPARTAMENTO DE MATEMÁTICA"]

,nome,sexo,formacao,vinculo,categoria,classe_funcional,lotacao,id_turma,ano,periodo,...,media_final_geral,qtd_aprovado,qtd_desistencia,qtd_reprovado_por_média_e_por_faltas,qtd_trancado,qtd_aprovado_por_nota,qtd_reprovado,qtd_reprovado_por_faltas,qtd_reprovado_por_nota_e_falta,qtd_reprovado_por_nota
28455,gAAAAABoK5E8s-l1HHWiAyHU_vmdxCAIVPbMQC9sg-Z_QY...,M,DOUTORADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,B ...,DEPARTAMENTO DE MATEMÁTICA,57704934,2022,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_merged.head(5)

,nome,sexo,formacao,vinculo,categoria,classe_funcional,lotacao,id_turma,ano,periodo,...,media_final_geral,qtd_aprovado,qtd_desistencia,qtd_reprovado_por_média_e_por_faltas,qtd_trancado,qtd_aprovado_por_nota,qtd_reprovado,qtd_reprovado_por_faltas,qtd_reprovado_por_nota_e_falta,qtd_reprovado_por_nota
0,gAAAAABoK5E6j5TbqZPDJ5NYzMxdBZriI-CsNEuDKbVirf...,M,MESTRADO,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,C ...,ESCOLA DE MÚSICA,57597342,2017,1,...,8.818182,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,gAAAAABoK5E6R1hu4dSPg8FkFOEIEmcEYHlYvmPJzZEPPd...,F,DOUTORADO,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,Classe A - Auxiliar ...,ESCOLA AGRÍCOLA DE JUNDIAÍ,1207402,2013,2,...,6.483333,6.0,0.0,0.0,1.0,0.0,11.0,0.0,0.0,0.0
2,gAAAAABoK5E6eAVCeUnbWC3nbkQx-aLvuBnJzHRQosKbFN...,F,DOUTORADO,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,Classe A - Auxiliar ...,ESCOLA AGRÍCOLA DE JUNDIAÍ,1224417,2014,1,...,8.557143,7.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
3,gAAAAABoK5E6qJDKzYFcqZH3pJgHamgSiwc4TQHNCtoo1d...,F,DOUTORADO,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,Classe A - Auxiliar ...,ESCOLA AGRÍCOLA DE JUNDIAÍ,1239782,2015,1,...,8.207692,13.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,gAAAAABoK5E6U5XZ1G27srNXBhH4mD1rnNwCC3N_ABu4Tw...,F,DOUTORADO,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,Classe A - Auxiliar ...,ESCOLA AGRÍCOLA DE JUNDIAÍ,1239821,2015,1,...,10.000000,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:

df_merged.sort_values('ano', ascending=False)

,nome,sexo,formacao,vinculo,categoria,classe_funcional,lotacao,id_turma,ano,periodo,...,media_final_geral,qtd_aprovado,qtd_desistencia,qtd_reprovado_por_média_e_por_faltas,qtd_trancado,qtd_aprovado_por_nota,qtd_reprovado,qtd_reprovado_por_faltas,qtd_reprovado_por_nota_e_falta,qtd_reprovado_por_nota
126291,gAAAAABoK5FCb9WzUw5eln4RvID5SLV_9x-1I9eIw3lEEP...,M,DOUTORADO,Professor Visitante,PROFESSOR MAGISTERIO SUPERIOR - VISITANTE,Adjunto ...,INSTITUTO DE POLÍTICAS PÚBLICAS,57736110,2024,1,...,8.437500,48.0,1.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0
126265,gAAAAABoK5FC5NAqZV_NS1w_lMufEMw-8Aqxd-C6Kahp5N...,M,DOUTORADO,Professor Visitante,PROFESSOR MAGISTERIO SUPERIOR - VISITANTE,A ...,DEPARTAMENTO DE HISTÓRIA,57733297,2024,1,...,9.443590,39.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0
126293,gAAAAABoK5FCtrhWeL5y7FNaN_QAMz-KAmYl-M6ceDfSVf...,M,DOUTORADO,Professor Visitante,PROFESSOR MAGISTERIO SUPERIOR - VISITANTE,Adjunto ...,INSTITUTO DE POLÍTICAS PÚBLICAS,57736116,2024,1,...,9.100000,10.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50964,gAAAAABoK5E9g1dMTqNVzyVenlo45XpHJtj05jKHhbef_Y...,F,DOUTORADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,A ...,FACULDADE DE CIÊNCIAS DA SAÚDE DO TRAIRI - FACISA,57731772,2024,1,...,9.181818,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126262,gAAAAABoK5FCHxIyOOtF1NgbN9UDuxbnXQNzuxuBtwozbc...,M,DOUTORADO,Professor Visitante,PROFESSOR MAGISTERIO SUPERIOR - VISITANTE,A ...,"FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOC...",57731472,2024,1,...,8.661765,34.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50966,gAAAAABoK5E9rFsGrmJFwMfDzPeBKh08irWWpe9PQ9sp-w...,F,MESTRADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,B ...,DEPARTAMENTO DE FUNDAMENTOS E POLÍTICAS DA EDU...,1209098,2013,2,...,8.108000,25.0,0.0,3.0,5.0,0.0,1.0,0.0,0.0,0.0
50965,gAAAAABoK5E9Nyzf-BTJUqKA6UhtMLRzBK_Ya5OMxrVW-g...,F,MESTRADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,B ...,DEPARTAMENTO DE FUNDAMENTOS E POLÍTICAS DA EDU...,1207583,2013,2,...,7.856250,32.0,3.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0
113619,gAAAAABoK5FBRJxLxOpIp8HrREf04BvkpTkdChfdA0ttd8...,F,DOUTORADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,C ...,DEPARTAMENTO DE ARQUITETURA,1212082,2013,2,...,8.445000,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113618,gAAAAABoK5FBEZ6wa6n88p2VQp1acdgFETmvuc3LyJujNQ...,F,DOUTORADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,C ...,DEPARTAMENTO DE ARQUITETURA,1212074,2013,2,...,7.665000,20.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9570,gAAAAABoK5E7kW8gFRVD2Pwd6BjMuGcPEQQVAEGndgR8i5...,F,DOUTORADO,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,D ...,DEPARTAMENTO DE NUTRIÇÃO,1212149,2013,2,...,7.402632,38.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0

In [33]:
df_merged.to_csv(
    '../CSVs/Finais/avaliacoes_Docentes_Turmas.csv',  # Nome do arquivo de saída
    index=False,                # Não incluir o índice no arquivo
    sep=';',                    # Separador (padrão é vírgula)
    header=True,                # Incluir cabeçalho
)