# Tratamento dos datasets [Situações de Discentes](https://dados.ufrn.br/dataset/situacoes-de-discentes)

O presente notebook aplica o processo de tratamento aos datasets de situações de discentes dos anos de 2013 à 2024.

Ao realizar os downloads dos .csvs, os datasets eram salvos com a extensão de arquivo .1 e .2 referentes ao período letivo dos respectivos anos (por exemplo, o dataset de 2013.1 era salvo como 'situacoes-discentes-2013.1' em vez de 'situacoes-discentes-2013-1.csv').

Desse modo, alterei manualmente o nome dos arquivos para 'situacoes-discentes-20XX-X.csv'.

Abaixo, estão dispostas as células para o tratamento destes .csv's e algumas análises superficiais para justificar a limpeza do dataframe.

OBS.: Carregarei no repositório APENAS A VERSÃO FINAL de 'situacoes-discentes', com dados de 2013 a 2024 referentes ao nível de ensino "GRADUAÇÃO".

In [1]:
import pandas as pd
import glob
import os

In [2]:
arquivos = os.path.join("../situacoes_discentes/situacoes-discentes-20*.csv")

lista_arquivos = sorted(glob.glob(arquivos))

for f in lista_arquivos:
    print(f"  - {os.path.basename(f)}")

  - situacoes-discentes-2013-1.csv
  - situacoes-discentes-2013-2.csv
  - situacoes-discentes-2014-1.csv
  - situacoes-discentes-2014-2.csv
  - situacoes-discentes-2015-1.csv
  - situacoes-discentes-2015-2.csv
  - situacoes-discentes-2016-1.csv
  - situacoes-discentes-2016-2.csv
  - situacoes-discentes-2017-1.csv
  - situacoes-discentes-2017-2.csv
  - situacoes-discentes-2018-1.csv
  - situacoes-discentes-2018-2.csv
  - situacoes-discentes-2019-1.csv
  - situacoes-discentes-2019-2.csv
  - situacoes-discentes-2020-1.csv
  - situacoes-discentes-2020-2.csv
  - situacoes-discentes-2021-1.csv
  - situacoes-discentes-2021-2.csv
  - situacoes-discentes-2022-1.csv
  - situacoes-discentes-2022-2.csv
  - situacoes-discentes-2023-1.csv
  - situacoes-discentes-2023-2.csv
  - situacoes-discentes-2024-1.csv
  - situacoes-discentes-2024-2.csv

In [3]:
lista_df = []

for arquivo in lista_arquivos:
    df_temp = pd.read_csv(arquivo, sep=None, engine='python')
    lista_df.append(df_temp)
    
df_concat = pd.concat(lista_df, ignore_index=True)

#df_concat = df_concat.to_csv("../databases/situacoes-discentes.csv", sep=';', index=False)

df_concat

,id_discente,ano_ingresso,periodo_ingresso,nivel_ensino,id_curso,curso,situacao,data_alteracao_situacao,ano_alteracao_situacao,periodo_alteracao_situacao
0,d1f679a90a07db5f5b3a14db60621df5,2009,1,MESTRADO,315785,MESTRADO EM MATEMÁTICA APLICADA E ESTATÍSTICA,ATIVO,2013/03/07 20:17:09.056000000,2013,1
1,d1f679a90a07db5f5b3a14db60621df5,2009,1,MESTRADO,315785,MESTRADO EM MATEMÁTICA APLICADA E ESTATÍSTICA,ATIVO,2013/03/07 20:19:48.225000000,2013,1
2,5185ce847f42059c429932cd47379112,2013,1,TÉCNICO,96054058,CURSO TÉCNICO DA METRÓPOLE DIGITAL,ATIVO,2013/01/07 09:23:42.724000000,2013,1
3,3eb19872e0e504662fa4f3dd19e11687,2013,1,TÉCNICO,96054058,CURSO TÉCNICO DA METRÓPOLE DIGITAL,CADASTRADO,2013/01/07 09:24:11.694000000,2013,1
4,ca653393f59ba2adf03d430dd12e094f,2013,1,TÉCNICO,96054058,CURSO TÉCNICO DA METRÓPOLE DIGITAL,CADASTRADO,2013/01/07 09:25:02.399000000,2013,1
...,...,...,...,...,...,...,...,...,...,...
1073383,4e444e12b62574bc5334896bc4c27f3d,2022,2,MESTRADO,155194753,MESTRADO PROFISSIONAL EM GESTÃO DA INFORMAÇÃO ...,EM HOMOLOGAÇÃO,2025/05/12 09:07:16.855000000,2024,2
1073384,b9b44adc104bb15dbee8b9a6abd25db2,2022,2,MESTRADO,155194753,MESTRADO PROFISSIONAL EM GESTÃO DA INFORMAÇÃO ...,EM HOMOLOGAÇÃO,2025/05/12 09:07:47.302000000,2024,2
1073385,e31a51dc58df89faed2a4c5433bc6950,2022,2,MESTRADO,155194753,MESTRADO PROFISSIONAL EM GESTÃO DA INFORMAÇÃO ...,EM HOMOLOGAÇÃO,2025/05/12 09:08:09.803000000,2024,2
1073386,beb613150a9ed7dcefd91419de03a689,2022,2,MESTRADO,155194753,MESTRADO PROFISSIONAL EM GESTÃO DA INFORMAÇÃO ...,DEFENDIDO,2025/05/28 07:06:03.261000000,2024,2
1073387,beb613150a9ed7dcefd91419de03a689,2022,2,MESTRADO,155194753,MESTRADO PROFISSIONAL EM GESTÃO DA INFORMAÇÃO ...,EM HOMOLOGAÇÃO,2025/05/28 11:10:44.318000000,2024,2

In [4]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073388 entries, 0 to 1073387
Data columns (total 10 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   id_discente                 1073388 non-null  object
 1   ano_ingresso                1073388 non-null  int64
 2   periodo_ingresso            1073388 non-null  int64
 3   nivel_ensino                1073388 non-null  object
 4   id_curso                    1073388 non-null  int64
 5   curso                       1073388 non-null  object
 6   situacao                    1073388 non-null  object
 7   data_alteracao_situacao     1073388 non-null  object
 8   ano_alteracao_situacao      1073388 non-null  int64
 9   periodo_alteracao_situacao  1073388 non-null  int64
dtypes: int64(5), object(5)
memory usage: 81.9+ MB

* De 2013.1 até 2024.2, temos 1.073.388 linhas no dataset
* Não há observação de valores faltantes
* Não é relevante para nossa análise manter a coluna 'data_alteracao_situacao'
* Atualmente, não é relevante para nossa análise manter discentes com nível de ensino diferente de graduação.

In [5]:
#remoção da data de alteração da situação do discente
df_concat = df_concat.drop(columns=['data_alteracao_situacao'])
#recorte da análise para discentes de graduação
df_concat = df_concat[df_concat['nivel_ensino'] == "GRADUAÇÃO"]

df_concat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 951714 entries, 5 to 1073190
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   id_discente                 951714 non-null  object
 1   ano_ingresso                951714 non-null  int64
 2   periodo_ingresso            951714 non-null  int64
 3   nivel_ensino                951714 non-null  object
 4   id_curso                    951714 non-null  int64
 5   curso                       951714 non-null  object
 6   situacao                    951714 non-null  object
 7   ano_alteracao_situacao      951714 non-null  int64
 8   periodo_alteracao_situacao  951714 non-null  int64
dtypes: int64(5), object(4)
memory usage: 72.6+ MB

* De 1.073.388 valores, agora temos 951.714

In [6]:
df_concat = df_concat.to_csv("../databases/situacoes-discentes.csv", sep=';', index=False)

In [7]:
situacao_disc = pd.read_csv("../databases/situacoes-discentes.csv", sep=';')

situacao_disc.describe()

,ano_ingresso,periodo_ingresso,id_curso,ano_alteracao_situacao,periodo_alteracao_situacao
count,951714.000000,951714.000000,9.517140e+05,951714.000000,951714.000000
mean,2017.066533,1.363055,2.821247e+07,2018.450582,1.394563
std,4.042523,0.480881,4.355988e+07,3.453479,0.488757
min,1974.000000,1.000000,2.000002e+06,2013.000000,1.000000
25%,2014.000000,1.000000,2.000034e+06,2015.000000,1.000000
50%,2017.000000,1.000000,2.576623e+06,2018.000000,1.000000
75%,2020.000000,2.000000,1.302779e+07,2021.000000,2.000000
max,2025.000000,2.000000,1.752250e+08,2024.000000,2.000000

In [8]:
situacao_disc.describe(include='object')

,id_discente,nivel_ensino,curso,situacao
count,951714,951714,951714,951714
unique,144793,1,91,7
top,28b1ebdb638d389c3dff2b030d24f76d,GRADUAÇÃO,CIÊNCIAS E TECNOLOGIA,CADASTRADO
freq,41,951714,139868,573295